When sending mail localy on a system compiled woth SASL AUTH, the sendmail mail submission program may log the following error on the sasldb file:
	error: safesasl(/usr/local/etc/sasldb) failed: Group readable file

Pine by default is using SMTP, and therfore SMTP AUTH if compiled
into sendmail.  To disable SMTP AUTH we need to define DAEMON_OPTIONS
for the loopback interface.

PR:		ports/51680
Submitted by:	Scot W. Hetzel <hetzels@westbend.net>