1. Fix build with clang:  [1] ----- clang -DHAVE_CONFIG_H -I. -I..  -I.. -I../libgamin -I../protocol -I../lib -I../libgamin -I/usr/local/include/glib-2.0 -DBINDIR=\""/usr/local/libexec"\" -DG_DISABLE_DEPRECATED -DGAM_DEBUG_ENABLED  -DHAVE_LINUX -I/usr/local/include  -Wall -Wchar-subscripts -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wsign-compare -Wno-sign-compare -g -O2 -pipe -fno-strict-aliasing -MT gam_eq.o -MD -MP -MF .deps/gam_eq.Tpo -c -o gam_eq.o gam_eq.c gam_eq.c:127:3: error: non-void function 'gam_eq_flush' should return a value [-Wreturn-type]                 return;                 ^ 1 error generated. -----
2. Do not bump PORTREVISION.
3. Since upstream is almost dead it's unlikely that this patch will
   be committed to it's repository.

Attn: GNOME has switched from gamin to gio. Seems that this port
may/should be deprecated...

Approved by:	gnome (mezz)  [1]
Discussed at:	freebsd-gnome