Add missing bitopts.h Change BROKEN_ELF->BROKEN as this is still BROKEN after the file addition.
In file included from ./treeview.c:44:
../../include/asm/bitops.h:8: redefinition of `set_bit'
../../include/asm/bitops.h:8: `set_bit' previously defined here
../../include/asm/bitops.h:18: redefinition of `clear_bit'
../../include/asm/bitops.h:18: `clear_bit' previously defined here
../../include/asm/bitops.h:28: redefinition of `change_bit'
../../include/asm/bitops.h:28: `change_bit' previously defined here
../../include/asm/bitops.h:38: redefinition of `test_bit'
../../include/asm/bitops.h:38: `test_bit' previously defined here
./treeview.c: In function `TREEVIEW_DrawItem':
./treeview.c:341: warning: unused variable `hRootPen'
./treeview.c:339: warning: `oldBkColor' might be used uninitialized in this function
*** Error code 1