Building security/libgcrypt 1.5.0 with clang results in errors similar to the following:
rijndael.c:846:46: error: ambiguous instructions require an explicit suffix (could be 'cmpb', 'cmpw', 'cmpl', or 'cmpq')
"movdqa 0xa0(%%esi), %%xmm1\n\t"
^
<inline asm>:24:2: note: instantiated into assembly here
cmp $10, -80(%ebp)
^

This is because the 'cmp' instruction lacks a type suffix, and is thus
ambiguous.  Fix this by changing these to 'cmpq'.

PR:	ports/158994
Approved by:	Hirohisa Yamaguchi <umq@ueo.co.jp> (maintainer)