Sortof fix msginit a little bit kindof. It was looking for certain files in the wrong place.
Before, running msginit would give this:
/usr/local/libdata/gettext/project-id: Can't open /usr/local/libdata/gettext/project-id: No such file or directory
msginit: /usr/local/libdata/gettext/project-id subprocess I/O error
/usr/local/libdata/gettext/user-email: Can't open /usr/local/libdata/gettext/user-email: No such file or directory
msginit: /usr/local/libdata/gettext/user-email subprocess I/O error
/usr/local/share/gettext/projects/TP/team-address: /usr/local/libdata/gettext/urlget: not found
etc.

Now, it gives this:
root@smacky:/usr/ports/GNOME/grm/i18n# msginit
The new message catalog should contain your email address, so that users can
give you feedback about the translations, and so that maintainers can contact
you in case of unexpected technical problems.

sed: 8: "{
h
s/^[^@]*@\(.*\)$/\1 ...": unterminated substitute pattern
Couldn't find out about your email address.
Please enter your email address.
adamw@gnome.org
sed: 8: "{
h
s/^[^@]*@\(.*\)$/\1 ...": unterminated substitute pattern
Exception in thread "main" java.lang.NoClassDefFoundError: gnu/gettext/GetURL

Someone should look into that new error.